name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to the GitHub Docker registry
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/blague-app:latest .

      # Push the Docker image to GitHub Packages
      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository }}/blague-app:latest
