name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Docker Registry
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/votre_nom_utilisateur/ue19_labo09-10/blague-app:latest .

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.45.0/trivy_0.45.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.45.0_Linux-64bit.deb

      # Scan Docker image with Trivy
      - name: Scan Docker image for vulnerabilities
        run: trivy image --ignore-unfixed --format table ghcr.io/votre_nom_utilisateur/ue19_labo09-10/blague-app:latest

      # Push the Docker image to GitHub Packages (only if the scan passes)
      - name: Push Docker image to GitHub Packages
        if: success()
        run: docker push ghcr.io/votre_nom_utilisateur/ue19_labo09-10/blague-app:latest
